#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_DIR="$HOME/.config/systemd/user"
UNIT_DIR="$SCRIPT_DIR/../systemd"
ENV_D_DIR="$HOME/.config/environment.d"
ENV_FILE="$SCRIPT_DIR/../.env.test"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: infra/.env.test not found. Copy .env.test.example and fill it in."
  exit 1
fi

# Read a value from .env.test
read_env() { grep "^${1}=" "$ENV_FILE" | cut -d= -f2- | tr -d '\r'; }

RELAY_PORT="$(read_env RELAY_PORT)"
RELAY_TOKEN="$(read_env RELAY_TOKEN)"
FRONTEND_PORT="$(read_env FRONTEND_PORT)"

if [ -z "$RELAY_PORT" ]; then echo "Error: RELAY_PORT not set in .env.test"; exit 1; fi

NODE_BIN="$(dirname "$(which node)")"
echo "Node: $NODE_BIN ($(node --version))"

mkdir -p "$ENV_D_DIR"
cat > "$ENV_D_DIR/alf-test.conf" <<EOF
# Generated by install-test.sh — re-run after switching node version or changing ports/token.
PATH=${NODE_BIN}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RELAY_URL=ws://localhost:${RELAY_PORT}
VITE_RELAY_URL=ws://localhost:${RELAY_PORT}/client
VITE_RELAY_TOKEN=${RELAY_TOKEN}
VITE_PORT=${FRONTEND_PORT}
EOF
echo "Wrote $ENV_D_DIR/alf-test.conf"

mkdir -p "$SYSTEMD_DIR"
cp "$UNIT_DIR"/alf-test*.service "$UNIT_DIR"/alf-test.target "$SYSTEMD_DIR/"

systemctl --user daemon-reload
systemctl --user enable alf-test.target

echo "Done. Start with:  systemctl --user start alf-test.target"
echo "Stop with:         systemctl --user stop alf-test.target"
