#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEMD_DIR="$HOME/.config/systemd/user"
UNIT_DIR="$SCRIPT_DIR/../systemd"
ENV_D_DIR="$HOME/.config/environment.d"
ENV_FILE="$SCRIPT_DIR/../.env.dev"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: infra/.env.dev not found. Copy .env.dev.example and fill it in."
  exit 1
fi

# Read a value from .env.dev (EnvironmentFile syntax doesn't support interpolation)
read_env() { grep "^${1}=" "$ENV_FILE" | cut -d= -f2- | tr -d '\r'; }

RELAY_PORT="$(read_env RELAY_PORT)"
RELAY_TOKEN="$(read_env RELAY_TOKEN)"

if [ -z "$RELAY_PORT" ]; then echo "Error: RELAY_PORT not set in .env.dev"; exit 1; fi

# Resolve node bin from the currently active version.
# Re-run this script after: nvm use <version>, or changing RELAY_PORT/TOKEN.
NODE_BIN="$(dirname "$(which node)")"
echo "Node: $NODE_BIN ($(node --version))"

# Write to environment.d — the systemd-native equivalent of sourcing .bashrc.
# Applies to all user services, so no need for hardcoded values in service files.
mkdir -p "$ENV_D_DIR"
cat > "$ENV_D_DIR/alf-dev.conf" <<EOF
# Generated by install-dev.sh — re-run after switching node version or changing ports/token.
PATH=${NODE_BIN}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RELAY_URL=ws://localhost:${RELAY_PORT}
VITE_RELAY_URL=ws://localhost:${RELAY_PORT}/client
VITE_RELAY_TOKEN=${RELAY_TOKEN}
EOF
echo "Wrote $ENV_D_DIR/alf-dev.conf"

mkdir -p "$SYSTEMD_DIR"
cp "$UNIT_DIR"/*.service "$UNIT_DIR"/*.target "$SYSTEMD_DIR/"

systemctl --user daemon-reload
systemctl --user enable alf-dev.target

echo "Done. Start with: systemctl --user start alf-dev.target"
